// This file is "movie_item.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
// required: associates our `main.dart` with the code generated by Freezed
part 'movie_item.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'movie_item.g.dart';

@freezed
class MovieItem with _$MovieItem {
  const factory MovieItem(
      {String? backdropPath,
        List<int>? genreIds,
        String? genres,
        int? id,
        String? originalLanguage,
        String? originalTitle,
        String? overview,
        double? popularity,
        String? posterPath,
        String? posterUrl,
        String? releaseDate,
        String? title,
        bool? video,
        double? voteAverage,
        String? formattedVoteAverage,
        int? voteCount}) = _MovieItem;

  factory MovieItem.fromJson(Map<String, Object?> json)
  => _$MovieItemFromJson(json);
}