// This file is "movie_item.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:movie/data/remote/response/genres_response.dart';
import 'package:movie/data/remote/response/movie_response.dart';
// required: associates our `main.dart` with the code generated by Freezed
part 'movie_detail.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'movie_detail.g.dart';

@freezed
class MovieDetail with _$MovieDetail {
  const factory MovieDetail(
      {bool? adult,
        String? backdropPath,
        String? backdropUrl,
        BelongsToCollection? belongsToCollection,
        int? budget,
        List<Genres>? genres,
        String? homepage,
        int? id,
        String? imdbId,
        List<String>? originCountry,
        String? originalLanguage,
        String? originalTitle,
        String? overview,
        double? popularity,
        String? posterPath,
        List<ProductionCompanies>? productionCompanies,
        List<ProductionCountries>? productionCountries,
        String? releaseDate,
        int? revenue,
        int? runtime,
        List<SpokenLanguages>? spokenLanguages,
        String? status,
        String? tagline,
        String? title,
        bool? video,
        double? voteAverage,
        int? voteCount}) = _MovieDetail;
  factory MovieDetail.fromJson(Map<String, Object?> json)
  => _$MovieDetailFromJson(json);
}